samples: samples.tsv
units: units.tsv

ref:
  #name: Sorghum_bicolor
  name: Sorghum_bicolor_NCBIv3.42
  # Path to the reference genome, ideally as it is provided by the GATK bundle.
  genome: genomes_and_annotations/Sorghum/Sbicolor_454_v3.0.1.fa
  # Path to any database of known variants, ideally as it is provided by the GATK bundle.
  known-variants: genomes_and_annotations/Sorghum/Sbicolor_Patterson_454.vcf.gz

filtering:
  # Set to true in order to apply machine learning based recalibration of
  # quality scores instead of hard filtering.
  vqsr: false
  hard:
    # hard filtering as outlined in GATK docs
    # (https://gatkforums.broadinstitute.org/gatk/discussion/2806/howto-apply-hard-filters-to-a-call-set)
    snvs:
      "QD < 2.0 || FS > 60.0 || MQ < 40.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0"
    indels:
      "QD < 2.0 || FS > 200.0 || ReadPosRankSum < -20.0"

processing:
  remove-duplicates: true
  # Uncomment and point to a bed file with, e.g., captured regions if necessary,
  # see https://gatkforums.broadinstitute.org/gatk/discussion/4133/when-should-i-use-l-to-pass-in-a-list-of-intervals.
  restrict-regions: regions_of_interest.bed
  # If regions are restricted, uncomment this to enlarge them by the given value in order to include
  # flanking areas.
  # region-padding: 100

params:
  gatk:
    HaplotypeCaller: "-ploidy 2 "
    BaseRecalibrator: ""
    GenotypeGVCFs: "--dbsnp genomes_and_annotations/Sorghum/Sbicolor_Patterson_454.vcf.gz "
    VariantRecalibrator: ""
  picard:
    MarkDuplicates: "REMOVE_DUPLICATES=true TMP_DIR=/mnt/norman/tmp/ "
  trimmomatic:
    pe:
      trimmer:
        # See trimmomatic manual for adding additional options, e.g. for adapter trimming.
        - "LEADING:3"
        - "TRAILING:3"
        - "SLIDINGWINDOW:4:15"
        - "MINLEN:36"
        - "ILLUMINACLIP:./adapter.fa:2:30:10:1:true"
    se:
      trimmer:
        # See trimmomatic manual for adding additional options, e.g. for adapter trimming.
        - "LEADING:3"
        - "TRAILING:3"
        - "SLIDINGWINDOW:4:15"
        - "MINLEN:36"
        - "ILLUMINACLIP:./adapter.fa:2:30:10:1:true"
